import React, { createContext, useContext, useState } from 'react';

// Supported languages in cycle order
export const LANGUAGES = [
  { code: 'id', label: 'Indonesia', flag: '🇮🇩', native: 'Bahasa Indonesia' },
  { code: 'en', label: 'English',   flag: '🇺🇸', native: 'English' },
  { code: 'ja', label: 'Japanese',  flag: '🇯🇵', native: '日本語' },
  { code: 'ko', label: 'Korean',    flag: '🇰🇷', native: '한국어' },
  { code: 'km', label: 'Khmer',     flag: '🇰🇭', native: 'ភាសាខ្មែរ' },
  { code: 'zh', label: 'Chinese',   flag: '🇨🇳', native: '中文' },
];

const translations = {
  id: {
    // Auth
    welcomeBack: 'Selamat Datang Kembali',
    loginSubtitle: 'Masuk ke akun Anda',
    email: 'Email',
    password: 'Kata Sandi',
    forgotPassword: 'Lupa kata sandi?',
    loginBtn: 'Masuk',
    loggingIn: 'Sedang masuk...',
    continueWithGoogle: 'Lanjutkan dengan Google',
    noAccount: 'Belum punya akun?',
    createOne: 'Daftar sekarang',
    invalidLogin: 'Email atau kata sandi salah',
    or: 'atau',
    // Register
    phoneNumber: 'Nomor HP',
    phoneOptional: 'Nomor HP (opsional)',
    phoneHint: 'Contoh: 08123456789',
    createAccount: 'Buat Akun Baru',
    registerSubtitle: 'Daftar untuk memulai',
    confirmPassword: 'Konfirmasi Kata Sandi',
    passwordMismatch: 'Kata sandi tidak cocok',
    registrationFailed: 'Pendaftaran gagal',
    creatingAccount: 'Membuat akun...',
    createAccountBtn: 'Buat Akun',
    alreadyHaveAccount: 'Sudah punya akun?',
    loginLink: 'Masuk',
    // OTP
    verifyEmail: 'Verifikasi Email',
    otpSent: 'Kode dikirim ke',
    verifying: 'Memverifikasi...',
    verify: 'Verifikasi',
    noCode: 'Tidak menerima kode?',
    resend: 'Kirim ulang',
    invalidOtp: 'Kode verifikasi tidak valid',
    resendFailed: 'Gagal mengirim ulang kode',
    codeSent: 'Kode terkirim',
    checkEmail: 'Cek email Anda untuk kode baru.',
    // Sidebar
    liveData: 'Data Langsung',
    lightMode: 'Mode Terang',
    darkMode: 'Mode Gelap',
    logout: 'Keluar',
    language: 'Bahasa',
    // Nav Groups
    dashboard: 'Dasbor',
    management: 'Manajemen',
    finance: 'Keuangan',
    system: 'Sistem',
    // Nav Items
    monthlyDashboard: 'Dashboard Bulanan',
    yearlyDashboard: 'Dashboard Tahunan',
    yoyComparison: 'Perbandingan Tahunan',
    budgetPlan: 'Budget Anggaran',
    financialGoals: 'Target Keuangan',
    inputTransaction: 'Input Transaksi',
    transactionHistory: 'Riwayat Transaksi',
    transferAccount: 'Transfer Saldo Bank',
    debt: 'Hutang',
    receivable: 'Piutang',
    accountBalance: 'Saldo Bank',
    netWorth: 'Kekayaan Bersih',
    settings: 'Pengaturan',
    activityLog: 'Log Aktivitas',
    featureGuide: 'Panduan Fitur',
    // NetWorth
    netWorthTitle: 'Pelacak Kekayaan Bersih',
    netWorthSubtitle: 'Pantau aset, kewajiban, dan nilai kekayaan bersih Anda',
    totalAssets: 'Total Aset',
    totalLiabilities: 'Total Kewajiban',
    netWorthLabel: 'Kekayaan Bersih',
    assetsAboveLiabilities: 'Aset > Kewajiban ✓',
    liabilitiesAboveAssets: 'Kewajiban > Aset ⚠️',
    comparisonByCurrency: 'Perbandingan per Mata Uang',
    assetsVsLiabilities: 'Aset vs Kewajiban',
    assetDistribution: 'Distribusi Aset',
    liabilityDistribution: 'Distribusi Kewajiban',
    summaryByCurrency: 'Ringkasan per Mata Uang',
    currency: 'Mata Uang',
    assets: 'Aset',
    liabilities: 'Kewajiban',
    noData: 'Belum ada data',
    noAssets: 'Belum ada aset',
    noLiabilities: 'Belum ada kewajiban',
    assetRatio: 'Rasio Aset',
    activeDebts: 'hutang aktif',
    accountsPlusReceivable: 'akun + piutang',
    total: 'Total',
    // Transaction
    amount: 'Nominal',
    amountPlaceholder: 'Masukkan nominal',
    date: 'Tanggal',
    description: 'Keterangan',
    category: 'Kategori',
    account: 'Akun',
    save: 'Simpan',
    cancel: 'Batal',
    delete: 'Hapus',
    edit: 'Edit',
    add: 'Tambah',
    search: 'Cari',
    filter: 'Filter',
    allMonths: 'Semua Bulan',
    allCurrencies: 'Semua Mata Uang',
    income: 'Pemasukan',
    expense: 'Pengeluaran',
    saving: 'Tabungan',
    transfer: 'Transfer',
    // Profile
    memberSince: 'Bergabung Sejak',
    activeStatus: 'Status Aktif',
    contactAdmin: 'Hubungi Admin',
    changePassword: 'Ganti Password',
    currentPassword: 'Password Saat Ini',
    newPassword: 'Password Baru',
    confirmNewPassword: 'Konfirmasi Password Baru',
    savePassword: 'Simpan Password',
    accessModules: 'Modul Akses',
    allFeaturesActive: 'Semua Fitur Aktif',
    // Dashboard
    financialDashboard: 'Financial Dashboard',
    monitorRealtime: 'Pantau kondisi keuangan Anda secara real-time',
    exportPDF: 'Export PDF',
    exporting: 'Mengekspor...',
    totalSaldo: 'Total Saldo',
    pendapatan: 'Pendapatan',
    pengeluaran: 'Pengeluaran',
    cashFlow: 'Cash Flow',
    tabungan: 'Tabungan',
    hutangAktif: 'Hutang Aktif',
    piutangAktif: 'Piutang Aktif',
    savingRate: 'Saving Rate',
    targetTercapai: '✓ Target tercapai',
    targetBelum: 'Target: >20%',
    trenAktivitas: 'Tren Aktivitas Keuangan',
    perbandinganBulan: 'Perbandingan bulan ke bulan',
    tahunan: 'Tahunan',
    pendapatanPerKategori: 'Pendapatan per Kategori',
    pengeluaranPerKategori: 'Pengeluaran per Kategori',
    tidakAdaPendapatan: 'Tidak ada data pendapatan',
    tidakAdaPengeluaran: 'Tidak ada data pengeluaran',
    distribusiSaldo: 'Distribusi Saldo Akun',
    perRekeningAktif: 'Per rekening aktif',
    belumAdaAkun: 'Belum ada akun terdaftar',
    hutangVsPiutang: 'Hutang vs Piutang',
    perbandinganAktif: 'Perbandingan aktif saat ini',
    rekapSaldo: 'Rekap Saldo Akun',
    saldoTerkini: 'Saldo terkini per rekening',
    insightKeuangan: 'Insight Keuangan',
    analisisCerdas: 'Analisis cerdas kondisi keuangan bulan ini',
    skorKesehatan: 'Skor Kesehatan Keuangan',
    top5Pengeluaran: 'Top 5 Pengeluaran Terbesar',
    berdasarkanKategori: 'Berdasarkan kategori',
    rekapPeriode: 'Rekap Periode',
    periode: 'Periode',
    kategoriFavorit: 'Kategori Favorit',
    totalAkun: 'Total Akun',
    totalTransaksi: 'Total Transaksi',
    semuaBulan: 'Semua Bulan',
  },

  en: {
    welcomeBack: 'Welcome Back',
    loginSubtitle: 'Log in to your account',
    email: 'Email',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    loginBtn: 'Log in',
    loggingIn: 'Logging in...',
    continueWithGoogle: 'Continue with Google',
    noAccount: "Don't have an account?",
    createOne: 'Create one',
    invalidLogin: 'Invalid email or password',
    or: 'or',
    phoneNumber: 'Phone Number',
    phoneOptional: 'Phone Number (optional)',
    phoneHint: 'e.g. +628123456789',
    createAccount: 'Create Account',
    registerSubtitle: 'Sign up to get started',
    confirmPassword: 'Confirm Password',
    passwordMismatch: 'Passwords do not match',
    registrationFailed: 'Registration failed',
    creatingAccount: 'Creating account...',
    createAccountBtn: 'Create Account',
    alreadyHaveAccount: 'Already have an account?',
    loginLink: 'Log in',
    verifyEmail: 'Verify your email',
    otpSent: 'We sent a code to',
    verifying: 'Verifying...',
    verify: 'Verify',
    noCode: "Didn't receive the code?",
    resend: 'Resend',
    invalidOtp: 'Invalid verification code',
    resendFailed: 'Failed to resend code',
    codeSent: 'Code sent',
    checkEmail: 'Check your email for the new code.',
    liveData: 'Live Data',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    logout: 'Logout',
    language: 'Language',
    dashboard: 'Dashboard',
    management: 'Management',
    finance: 'Finance',
    system: 'System',
    monthlyDashboard: 'Monthly Dashboard',
    yearlyDashboard: 'Yearly Dashboard',
    yoyComparison: 'Year-over-Year',
    budgetPlan: 'Budget Plan',
    financialGoals: 'Financial Goals',
    inputTransaction: 'Input Transaction',
    transactionHistory: 'Transaction History',
    transferAccount: 'Transfer Bank Balance',
    debt: 'Debt',
    receivable: 'Receivable',
    accountBalance: 'Bank Balance',
    netWorth: 'Net Worth',
    settings: 'Settings',
    activityLog: 'Activity Log',
    featureGuide: 'Feature Guide',
    netWorthTitle: 'Net Worth Tracker',
    netWorthSubtitle: 'Track your assets, liabilities, and net worth',
    totalAssets: 'Total Assets',
    totalLiabilities: 'Total Liabilities',
    netWorthLabel: 'Net Worth',
    assetsAboveLiabilities: 'Assets > Liabilities ✓',
    liabilitiesAboveAssets: 'Liabilities > Assets ⚠️',
    comparisonByCurrency: 'Comparison by Currency',
    assetsVsLiabilities: 'Assets vs Liabilities',
    assetDistribution: 'Asset Distribution',
    liabilityDistribution: 'Liability Distribution',
    summaryByCurrency: 'Summary by Currency',
    currency: 'Currency',
    assets: 'Assets',
    liabilities: 'Liabilities',
    noData: 'No data yet',
    noAssets: 'No assets yet',
    noLiabilities: 'No liabilities yet',
    assetRatio: 'Asset Ratio',
    activeDebts: 'active debts',
    accountsPlusReceivable: 'accounts + receivables',
    total: 'Total',
    amount: 'Amount',
    amountPlaceholder: 'Enter amount',
    date: 'Date',
    description: 'Description',
    category: 'Category',
    account: 'Account',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    search: 'Search',
    filter: 'Filter',
    allMonths: 'All Months',
    allCurrencies: 'All Currencies',
    income: 'Income',
    expense: 'Expense',
    saving: 'Saving',
    transfer: 'Transfer',
    memberSince: 'Member Since',
    activeStatus: 'Active Status',
    contactAdmin: 'Contact Admin',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    savePassword: 'Save Password',
    accessModules: 'Access Modules',
    allFeaturesActive: 'All Features Active',
    financialDashboard: 'Financial Dashboard',
    monitorRealtime: 'Monitor your finances in real-time',
    exportPDF: 'Export PDF',
    exporting: 'Exporting...',
    totalSaldo: 'Total Balance',
    pendapatan: 'Income',
    pengeluaran: 'Expenses',
    cashFlow: 'Cash Flow',
    tabungan: 'Savings',
    hutangAktif: 'Active Debt',
    piutangAktif: 'Active Receivable',
    savingRate: 'Saving Rate',
    targetTercapai: '✓ Target achieved',
    targetBelum: 'Target: >20%',
    trenAktivitas: 'Financial Activity Trend',
    perbandinganBulan: 'Month-over-month comparison',
    tahunan: 'Annual',
    pendapatanPerKategori: 'Income by Category',
    pengeluaranPerKategori: 'Expenses by Category',
    tidakAdaPendapatan: 'No income data',
    tidakAdaPengeluaran: 'No expense data',
    distribusiSaldo: 'Account Balance Distribution',
    perRekeningAktif: 'Per active account',
    belumAdaAkun: 'No accounts registered yet',
    hutangVsPiutang: 'Debt vs Receivable',
    perbandinganAktif: 'Current active comparison',
    rekapSaldo: 'Account Balance Summary',
    saldoTerkini: 'Current balance per account',
    insightKeuangan: 'Financial Insights',
    analisisCerdas: 'Smart analysis of this month\'s finances',
    skorKesehatan: 'Financial Health Score',
    top5Pengeluaran: 'Top 5 Biggest Expenses',
    berdasarkanKategori: 'By category',
    rekapPeriode: 'Period Summary',
    periode: 'Period',
    kategoriFavorit: 'Favorite Categories',
    totalAkun: 'Total Accounts',
    totalTransaksi: 'Total Transactions',
    semuaBulan: 'All Months',
  },

  ja: {
    welcomeBack: 'おかえりなさい',
    loginSubtitle: 'アカウントにログイン',
    email: 'メール',
    password: 'パスワード',
    forgotPassword: 'パスワードを忘れた？',
    loginBtn: 'ログイン',
    loggingIn: 'ログイン中...',
    continueWithGoogle: 'Googleで続ける',
    noAccount: 'アカウントをお持ちでない？',
    createOne: '今すぐ登録',
    invalidLogin: 'メールまたはパスワードが正しくありません',
    or: 'または',
    phoneNumber: '電話番号',
    phoneOptional: '電話番号（任意）',
    phoneHint: '例: 08123456789',
    createAccount: 'アカウント作成',
    registerSubtitle: '登録して始めましょう',
    confirmPassword: 'パスワード確認',
    passwordMismatch: 'パスワードが一致しません',
    registrationFailed: '登録に失敗しました',
    creatingAccount: 'アカウント作成中...',
    createAccountBtn: 'アカウント作成',
    alreadyHaveAccount: 'すでにアカウントをお持ちですか？',
    loginLink: 'ログイン',
    verifyEmail: 'メール認証',
    otpSent: 'コードを送信しました',
    verifying: '確認中...',
    verify: '確認',
    noCode: 'コードが届かない？',
    resend: '再送信',
    invalidOtp: '認証コードが無効です',
    resendFailed: '再送信に失敗しました',
    codeSent: 'コードを送信しました',
    checkEmail: '新しいコードはメールをご確認ください。',
    liveData: 'ライブデータ',
    lightMode: 'ライトモード',
    darkMode: 'ダークモード',
    logout: 'ログアウト',
    language: '言語',
    dashboard: 'ダッシュボード',
    management: '管理',
    finance: '財務',
    system: 'システム',
    monthlyDashboard: '月次ダッシュボード',
    yearlyDashboard: '年次ダッシュボード',
    yoyComparison: '年次比較',
    budgetPlan: '予算計画',
    financialGoals: '財務目標',
    inputTransaction: '取引入力',
    transactionHistory: '取引履歴',
    transferAccount: '口座振替',
    debt: '負債',
    receivable: '売掛金',
    accountBalance: '口座残高',
    netWorth: '純資産',
    settings: '設定',
    activityLog: '活動ログ',
    featureGuide: '機能ガイド',
    netWorthTitle: '純資産トラッカー',
    netWorthSubtitle: '資産、負債、純資産を追跡',
    totalAssets: '総資産',
    totalLiabilities: '総負債',
    netWorthLabel: '純資産',
    assetsAboveLiabilities: '資産 > 負債 ✓',
    liabilitiesAboveAssets: '負債 > 資産 ⚠️',
    comparisonByCurrency: '通貨別比較',
    assetsVsLiabilities: '資産 vs 負債',
    assetDistribution: '資産分布',
    liabilityDistribution: '負債分布',
    summaryByCurrency: '通貨別サマリー',
    currency: '通貨',
    assets: '資産',
    liabilities: '負債',
    noData: 'データなし',
    noAssets: '資産なし',
    noLiabilities: '負債なし',
    assetRatio: '資産比率',
    activeDebts: 'アクティブな負債',
    accountsPlusReceivable: '口座 + 売掛金',
    total: '合計',
    amount: '金額',
    amountPlaceholder: '金額を入力',
    date: '日付',
    description: '説明',
    category: 'カテゴリ',
    account: '口座',
    save: '保存',
    cancel: 'キャンセル',
    delete: '削除',
    edit: '編集',
    add: '追加',
    search: '検索',
    filter: 'フィルター',
    allMonths: '全月',
    allCurrencies: '全通貨',
    income: '収入',
    expense: '支出',
    saving: '貯蓄',
    transfer: '振替',
    memberSince: '会員登録日',
    activeStatus: 'アクティブ状態',
    contactAdmin: '管理者に連絡',
    changePassword: 'パスワード変更',
    currentPassword: '現在のパスワード',
    newPassword: '新しいパスワード',
    confirmNewPassword: '新しいパスワードを確認',
    savePassword: 'パスワードを保存',
    accessModules: 'アクセスモジュール',
    allFeaturesActive: '全機能アクティブ',
    financialDashboard: 'ファイナンシャルダッシュボード',
    monitorRealtime: 'リアルタイムで財務状況を確認',
    exportPDF: 'PDF出力',
    exporting: 'エクスポート中...',
    totalSaldo: '総残高',
    pendapatan: '収入',
    pengeluaran: '支出',
    cashFlow: 'キャッシュフロー',
    tabungan: '貯蓄',
    hutangAktif: '活性負債',
    piutangAktif: '活性売掛金',
    savingRate: '貯蓄率',
    targetTercapai: '✓ 目標達成',
    targetBelum: '目標: >20%',
    trenAktivitas: '財務活動トレンド',
    perbandinganBulan: '月次比較',
    tahunan: '年次',
    pendapatanPerKategori: 'カテゴリ別収入',
    pengeluaranPerKategori: 'カテゴリ別支出',
    tidakAdaPendapatan: '収入データなし',
    tidakAdaPengeluaran: '支出データなし',
    distribusiSaldo: '口座残高分布',
    perRekeningAktif: 'アクティブ口座別',
    belumAdaAkun: '口座が登録されていません',
    hutangVsPiutang: '負債 vs 売掛金',
    perbandinganAktif: '現在の比較',
    rekapSaldo: '口座残高概要',
    saldoTerkini: '口座別最新残高',
    insightKeuangan: '財務インサイト',
    analisisCerdas: '今月の財務スマート分析',
    skorKesehatan: '財務健全性スコア',
    top5Pengeluaran: '支出トップ5',
    berdasarkanKategori: 'カテゴリ別',
    rekapPeriode: '期間サマリー',
    periode: '期間',
    kategoriFavorit: 'お気に入りカテゴリ',
    totalAkun: '総口座数',
    totalTransaksi: '総取引数',
    semuaBulan: '全月',
  },

  ko: {
    welcomeBack: '다시 오신 것을 환영합니다',
    loginSubtitle: '계정에 로그인',
    email: '이메일',
    password: '비밀번호',
    forgotPassword: '비밀번호를 잊으셨나요?',
    loginBtn: '로그인',
    loggingIn: '로그인 중...',
    continueWithGoogle: 'Google로 계속',
    noAccount: '계정이 없으신가요?',
    createOne: '지금 가입',
    invalidLogin: '이메일 또는 비밀번호가 잘못되었습니다',
    or: '또는',
    phoneNumber: '전화번호',
    phoneOptional: '전화번호 (선택)',
    phoneHint: '예: 08123456789',
    createAccount: '계정 만들기',
    registerSubtitle: '가입하여 시작하세요',
    confirmPassword: '비밀번호 확인',
    passwordMismatch: '비밀번호가 일치하지 않습니다',
    registrationFailed: '등록에 실패했습니다',
    creatingAccount: '계정 생성 중...',
    createAccountBtn: '계정 만들기',
    alreadyHaveAccount: '이미 계정이 있으신가요?',
    loginLink: '로그인',
    verifyEmail: '이메일 인증',
    otpSent: '코드를 전송했습니다',
    verifying: '확인 중...',
    verify: '확인',
    noCode: '코드를 받지 못하셨나요?',
    resend: '다시 전송',
    invalidOtp: '인증 코드가 유효하지 않습니다',
    resendFailed: '재전송에 실패했습니다',
    codeSent: '코드 전송됨',
    checkEmail: '새 코드는 이메일을 확인하세요.',
    liveData: '실시간 데이터',
    lightMode: '라이트 모드',
    darkMode: '다크 모드',
    logout: '로그아웃',
    language: '언어',
    dashboard: '대시보드',
    management: '관리',
    finance: '재무',
    system: '시스템',
    monthlyDashboard: '월간 대시보드',
    yearlyDashboard: '연간 대시보드',
    yoyComparison: '연간 비교',
    budgetPlan: '예산 계획',
    financialGoals: '재무 목표',
    inputTransaction: '거래 입력',
    transactionHistory: '거래 내역',
    transferAccount: '계좌 이체',
    debt: '부채',
    receivable: '매출채권',
    accountBalance: '계좌 잔액',
    netWorth: '순자산',
    settings: '설정',
    activityLog: '활동 로그',
    featureGuide: '기능 가이드',
    netWorthTitle: '순자산 트래커',
    netWorthSubtitle: '자산, 부채 및 순자산 추적',
    totalAssets: '총 자산',
    totalLiabilities: '총 부채',
    netWorthLabel: '순자산',
    assetsAboveLiabilities: '자산 > 부채 ✓',
    liabilitiesAboveAssets: '부채 > 자산 ⚠️',
    comparisonByCurrency: '통화별 비교',
    assetsVsLiabilities: '자산 vs 부채',
    assetDistribution: '자산 분포',
    liabilityDistribution: '부채 분포',
    summaryByCurrency: '통화별 요약',
    currency: '통화',
    assets: '자산',
    liabilities: '부채',
    noData: '데이터 없음',
    noAssets: '자산 없음',
    noLiabilities: '부채 없음',
    assetRatio: '자산 비율',
    activeDebts: '활성 부채',
    accountsPlusReceivable: '계좌 + 매출채권',
    total: '합계',
    amount: '금액',
    amountPlaceholder: '금액 입력',
    date: '날짜',
    description: '설명',
    category: '카테고리',
    account: '계좌',
    save: '저장',
    cancel: '취소',
    delete: '삭제',
    edit: '수정',
    add: '추가',
    search: '검색',
    filter: '필터',
    allMonths: '전체 월',
    allCurrencies: '전체 통화',
    income: '수입',
    expense: '지출',
    saving: '저축',
    transfer: '이체',
    memberSince: '가입일',
    activeStatus: '활성 상태',
    contactAdmin: '관리자 문의',
    changePassword: '비밀번호 변경',
    currentPassword: '현재 비밀번호',
    newPassword: '새 비밀번호',
    confirmNewPassword: '새 비밀번호 확인',
    savePassword: '비밀번호 저장',
    accessModules: '접근 모듈',
    allFeaturesActive: '모든 기능 활성',
    financialDashboard: '재무 대시보드',
    monitorRealtime: '실시간으로 재무 상태를 모니터링',
    exportPDF: 'PDF 내보내기',
    exporting: '내보내는 중...',
    totalSaldo: '총 잔액',
    pendapatan: '수입',
    pengeluaran: '지출',
    cashFlow: '현금 흐름',
    tabungan: '저축',
    hutangAktif: '활성 부채',
    piutangAktif: '활성 매출채권',
    savingRate: '저축률',
    targetTercapai: '✓ 목표 달성',
    targetBelum: '목표: >20%',
    trenAktivitas: '재무 활동 추이',
    perbandinganBulan: '월별 비교',
    tahunan: '연간',
    pendapatanPerKategori: '카테고리별 수입',
    pengeluaranPerKategori: '카테고리별 지출',
    tidakAdaPendapatan: '수입 데이터 없음',
    tidakAdaPengeluaran: '지출 데이터 없음',
    distribusiSaldo: '계좌 잔액 분포',
    perRekeningAktif: '활성 계좌별',
    belumAdaAkun: '등록된 계좌 없음',
    hutangVsPiutang: '부채 vs 매출채권',
    perbandinganAktif: '현재 비교',
    rekapSaldo: '계좌 잔액 요약',
    saldoTerkini: '계좌별 최신 잔액',
    insightKeuangan: '재무 인사이트',
    analisisCerdas: '이번 달 스마트 재무 분석',
    skorKesehatan: '재무 건강 점수',
    top5Pengeluaran: '지출 상위 5개',
    berdasarkanKategori: '카테고리별',
    rekapPeriode: '기간 요약',
    periode: '기간',
    kategoriFavorit: '즐겨찾기 카테고리',
    totalAkun: '총 계좌 수',
    totalTransaksi: '총 거래 수',
    semuaBulan: '전체 월',
  },

  km: {
    welcomeBack: 'សូមស្វាគមន៍វិញ',
    loginSubtitle: 'ចូលទៅក្នុងគណនីរបស់អ្នក',
    email: 'អ៊ីមែល',
    password: 'ពាក្យសម្ងាត់',
    forgotPassword: 'ភ្លេចពាក្យសម្ងាត់?',
    loginBtn: 'ចូល',
    loggingIn: 'កំពុងចូល...',
    continueWithGoogle: 'បន្តជាមួយ Google',
    noAccount: 'មិនមានគណនីទេ?',
    createOne: 'ចុះឈ្មោះឥឡូវ',
    invalidLogin: 'អ៊ីមែល ឬ ពាក្យសម្ងាត់មិនត្រឹមត្រូវ',
    or: 'ឬ',
    phoneNumber: 'លេខទូរស័ព្ទ',
    phoneOptional: 'លេខទូរស័ព្ទ (ស្រេចចិត្ត)',
    phoneHint: 'ឧទា: 08123456789',
    createAccount: 'បង្កើតគណនី',
    registerSubtitle: 'ចុះឈ្មោះដើម្បីចាប់ផ្តើម',
    confirmPassword: 'បញ្ជាក់ពាក្យសម្ងាត់',
    passwordMismatch: 'ពាក្យសម្ងាត់មិនត្រូវគ្នា',
    registrationFailed: 'ការចុះឈ្មោះបានបរាជ័យ',
    creatingAccount: 'កំពុងបង្កើតគណនី...',
    createAccountBtn: 'បង្កើតគណនី',
    alreadyHaveAccount: 'មានគណនីរួចហើយ?',
    loginLink: 'ចូល',
    verifyEmail: 'ផ្ទៀងផ្ទាត់អ៊ីមែល',
    otpSent: 'លេខកូដបានផ្ញើទៅ',
    verifying: 'កំពុងផ្ទៀងផ្ទាត់...',
    verify: 'ផ្ទៀងផ្ទាត់',
    noCode: 'មិនទទួលបានលេខកូដ?',
    resend: 'ផ្ញើម្ដងទៀត',
    invalidOtp: 'លេខកូដផ្ទៀងផ្ទាត់មិនត្រឹមត្រូវ',
    resendFailed: 'ការផ្ញើម្ដងទៀតបានបរាជ័យ',
    codeSent: 'បានផ្ញើលេខកូដ',
    checkEmail: 'ពិនិត្យអ៊ីមែលរបស់អ្នកសម្រាប់លេខកូដថ្មី។',
    liveData: 'ទិន្នន័យផ្ទាល់',
    lightMode: 'របៀបភ្លឺ',
    darkMode: 'របៀបងងឹត',
    logout: 'ចេញ',
    language: 'ភាសា',
    dashboard: 'ផ្ទាំងគ្រប់គ្រង',
    management: 'ការគ្រប់គ្រង',
    finance: 'ហិរញ្ញវត្ថុ',
    system: 'ប្រព័ន្ធ',
    monthlyDashboard: 'ផ្ទាំងប្រចាំខែ',
    yearlyDashboard: 'ផ្ទាំងប្រចាំឆ្នាំ',
    yoyComparison: 'ការប្រៀបធៀបប្រចាំឆ្នាំ',
    budgetPlan: 'ផែនការថវិកា',
    financialGoals: 'គោលដៅហិរញ្ញវត្ថុ',
    inputTransaction: 'បញ្ចូលប្រតិបត្តិការ',
    transactionHistory: 'ប្រវត្តិប្រតិបត្តិការ',
    transferAccount: 'ផ្ទេរសាច់ប្រាក់',
    debt: 'បំណុល',
    receivable: 'គណនីទទួល',
    accountBalance: 'សមតុល្យគណនី',
    netWorth: 'ទ្រព្យសម្បត្តិសុទ្ធ',
    settings: 'ការកំណត់',
    activityLog: 'កំណត់ហេតុសកម្មភាព',
    featureGuide: 'មគ្គុទ្ទេសក៍មុខងារ',
    netWorthTitle: 'ម៉ូនីទ័រទ្រព្យសម្បត្តិសុទ្ធ',
    netWorthSubtitle: 'តាមដានទ្រព្យសម្បត្តិ បំណុល និងទ្រព្យសម្បត្តិសុទ្ធ',
    totalAssets: 'ទ្រព្យសម្បត្តិសរុប',
    totalLiabilities: 'បំណុលសរុប',
    netWorthLabel: 'ទ្រព្យសម្បត្តិសុទ្ធ',
    assetsAboveLiabilities: 'ទ្រព្យ > បំណុល ✓',
    liabilitiesAboveAssets: 'បំណុល > ទ្រព្យ ⚠️',
    comparisonByCurrency: 'ការប្រៀបធៀបតាមរូបិយប័ណ្ណ',
    assetsVsLiabilities: 'ទ្រព្យ vs បំណុល',
    assetDistribution: 'ការបែងចែកទ្រព្យ',
    liabilityDistribution: 'ការបែងចែកបំណុល',
    summaryByCurrency: 'សង្ខេបតាមរូបិយប័ណ្ណ',
    currency: 'រូបិយប័ណ្ណ',
    assets: 'ទ្រព្យ',
    liabilities: 'បំណុល',
    noData: 'មិនមានទិន្នន័យ',
    noAssets: 'មិនមានទ្រព្យ',
    noLiabilities: 'មិនមានបំណុល',
    assetRatio: 'សមាមាត្រទ្រព្យ',
    activeDebts: 'បំណុលសកម្ម',
    accountsPlusReceivable: 'គណនី + គណនីទទួល',
    total: 'សរុប',
    amount: 'ចំនួន',
    amountPlaceholder: 'បញ្ចូលចំនួន',
    date: 'កាលបរិច្ឆេទ',
    description: 'ការពិពណ៌នា',
    category: 'ប្រភេទ',
    account: 'គណនី',
    save: 'រក្សាទុក',
    cancel: 'បោះបង់',
    delete: 'លុប',
    edit: 'កែប្រែ',
    add: 'បន្ថែម',
    search: 'ស្វែងរក',
    filter: 'ត្រង',
    allMonths: 'គ្រប់ខែ',
    allCurrencies: 'គ្រប់រូបិយប័ណ្ណ',
    income: 'ចំណូល',
    expense: 'ចំណាយ',
    saving: 'សន្សំ',
    transfer: 'ផ្ទេរ',
    memberSince: 'សមាជិកតាំងពី',
    activeStatus: 'ស្ថានភាពសកម្ម',
    contactAdmin: 'ទាក់ទងអ្នកគ្រប់គ្រង',
    changePassword: 'ផ្លាស់ប្តូរពាក្យសម្ងាត់',
    currentPassword: 'ពាក្យសម្ងាត់បច្ចុប្បន្ន',
    newPassword: 'ពាក្យសម្ងាត់ថ្មី',
    confirmNewPassword: 'បញ្ជាក់ពាក្យសម្ងាត់ថ្មី',
    savePassword: 'រក្សាទុកពាក្យសម្ងាត់',
    accessModules: 'ម៉ូឌុលចូល',
    allFeaturesActive: 'មុខងារទាំងអស់សកម្ម',
    financialDashboard: 'ផ្ទាំងហិរញ្ញវត្ថុ',
    monitorRealtime: 'តាមដានហិរញ្ញវត្ថុរបស់អ្នកក្នុងពេលវេលាជាក់ស្ដែង',
    exportPDF: 'នាំចេញ PDF',
    exporting: 'កំពុងនាំចេញ...',
    totalSaldo: 'សមតុល្យសរុប',
    pendapatan: 'ចំណូល',
    pengeluaran: 'ចំណាយ',
    cashFlow: 'លំហូរសាច់ប្រាក់',
    tabungan: 'សន្សំ',
    hutangAktif: 'បំណុលសកម្ម',
    piutangAktif: 'គណនីទទួលសកម្ម',
    savingRate: 'អត្រាសន្សំ',
    targetTercapai: '✓ គោលដៅសម្រេច',
    targetBelum: 'គោលដៅ: >20%',
    trenAktivitas: 'និន្នាការសកម្មភាពហិរញ្ញវត្ថុ',
    perbandinganBulan: 'ការប្រៀបធៀបខែ',
    tahunan: 'ប្រចាំឆ្នាំ',
    pendapatanPerKategori: 'ចំណូលតាមប្រភេទ',
    pengeluaranPerKategori: 'ចំណាយតាមប្រភេទ',
    tidakAdaPendapatan: 'គ្មានទិន្នន័យចំណូល',
    tidakAdaPengeluaran: 'គ្មានទិន្នន័យចំណាយ',
    distribusiSaldo: 'ការបែងចែកសមតុល្យគណនី',
    perRekeningAktif: 'ក្នុងគណនីសកម្ម',
    belumAdaAkun: 'មិនទាន់មានគណនី',
    hutangVsPiutang: 'បំណុល vs គណនីទទួល',
    perbandinganAktif: 'ការប្រៀបធៀបបច្ចុប្បន្ន',
    rekapSaldo: 'សង្ខេបសមតុល្យគណនី',
    saldoTerkini: 'សមតុល្យចុងក្រោយក្នុងគណនី',
    insightKeuangan: 'ការយល់ដឹងហិរញ្ញវត្ថុ',
    analisisCerdas: 'ការវិភាគឆ្លាតវៃសម្រាប់ខែនេះ',
    skorKesehatan: 'ពិន្ទុសុខភាពហិរញ្ញវត្ថុ',
    top5Pengeluaran: 'ចំណាយ 5 ខ្ពស់បំផុត',
    berdasarkanKategori: 'តាមប្រភេទ',
    rekapPeriode: 'សង្ខេបរយៈពេល',
    periode: 'រយៈពេល',
    kategoriFavorit: 'ប្រភេទពេញចិត្ត',
    totalAkun: 'គណនីសរុប',
    totalTransaksi: 'ប្រតិបត្តិការសរុប',
    semuaBulan: 'គ្រប់ខែ',
  },

  zh: {
    welcomeBack: '欢迎回来',
    loginSubtitle: '登录您的账户',
    email: '邮箱',
    password: '密码',
    forgotPassword: '忘记密码？',
    loginBtn: '登录',
    loggingIn: '登录中...',
    continueWithGoogle: '使用Google继续',
    noAccount: '没有账户？',
    createOne: '立即注册',
    invalidLogin: '邮箱或密码错误',
    or: '或',
    phoneNumber: '手机号',
    phoneOptional: '手机号（可选）',
    phoneHint: '例如: 08123456789',
    createAccount: '创建账户',
    registerSubtitle: '注册开始使用',
    confirmPassword: '确认密码',
    passwordMismatch: '密码不匹配',
    registrationFailed: '注册失败',
    creatingAccount: '创建账户中...',
    createAccountBtn: '创建账户',
    alreadyHaveAccount: '已有账户？',
    loginLink: '登录',
    verifyEmail: '验证邮箱',
    otpSent: '验证码已发送到',
    verifying: '验证中...',
    verify: '验证',
    noCode: '没有收到验证码？',
    resend: '重新发送',
    invalidOtp: '验证码无效',
    resendFailed: '重新发送失败',
    codeSent: '验证码已发送',
    checkEmail: '请检查您的邮箱获取新验证码。',
    liveData: '实时数据',
    lightMode: '亮色模式',
    darkMode: '暗色模式',
    logout: '退出',
    language: '语言',
    dashboard: '仪表板',
    management: '管理',
    finance: '财务',
    system: '系统',
    monthlyDashboard: '月度仪表板',
    yearlyDashboard: '年度仪表板',
    yoyComparison: '年度对比',
    budgetPlan: '预算计划',
    financialGoals: '财务目标',
    inputTransaction: '输入交易',
    transactionHistory: '交易历史',
    transferAccount: '转账',
    debt: '债务',
    receivable: '应收账款',
    accountBalance: '账户余额',
    netWorth: '净资产',
    settings: '设置',
    activityLog: '活动日志',
    featureGuide: '功能指南',
    netWorthTitle: '净资产追踪器',
    netWorthSubtitle: '追踪您的资产、负债和净资产',
    totalAssets: '总资产',
    totalLiabilities: '总负债',
    netWorthLabel: '净资产',
    assetsAboveLiabilities: '资产 > 负债 ✓',
    liabilitiesAboveAssets: '负债 > 资产 ⚠️',
    comparisonByCurrency: '按货币比较',
    assetsVsLiabilities: '资产 vs 负债',
    assetDistribution: '资产分布',
    liabilityDistribution: '负债分布',
    summaryByCurrency: '按货币汇总',
    currency: '货币',
    assets: '资产',
    liabilities: '负债',
    noData: '暂无数据',
    noAssets: '暂无资产',
    noLiabilities: '暂无负债',
    assetRatio: '资产比率',
    activeDebts: '活跃债务',
    accountsPlusReceivable: '账户 + 应收',
    total: '合计',
    amount: '金额',
    amountPlaceholder: '请输入金额',
    date: '日期',
    description: '描述',
    category: '类别',
    account: '账户',
    save: '保存',
    cancel: '取消',
    delete: '删除',
    edit: '编辑',
    add: '添加',
    search: '搜索',
    filter: '筛选',
    allMonths: '全部月份',
    allCurrencies: '全部货币',
    income: '收入',
    expense: '支出',
    saving: '储蓄',
    transfer: '转账',
    memberSince: '加入时间',
    activeStatus: '活跃状态',
    contactAdmin: '联系管理员',
    changePassword: '更改密码',
    currentPassword: '当前密码',
    newPassword: '新密码',
    confirmNewPassword: '确认新密码',
    savePassword: '保存密码',
    accessModules: '访问模块',
    allFeaturesActive: '所有功能已激活',
    financialDashboard: '财务仪表板',
    monitorRealtime: '实时监控您的财务状况',
    exportPDF: '导出PDF',
    exporting: '导出中...',
    totalSaldo: '总余额',
    pendapatan: '收入',
    pengeluaran: '支出',
    cashFlow: '现金流',
    tabungan: '储蓄',
    hutangAktif: '活跃债务',
    piutangAktif: '活跃应收',
    savingRate: '储蓄率',
    targetTercapai: '✓ 目标达成',
    targetBelum: '目标: >20%',
    trenAktivitas: '财务活动趋势',
    perbandinganBulan: '月度环比',
    tahunan: '年度',
    pendapatanPerKategori: '按类别收入',
    pengeluaranPerKategori: '按类别支出',
    tidakAdaPendapatan: '暂无收入数据',
    tidakAdaPengeluaran: '暂无支出数据',
    distribusiSaldo: '账户余额分布',
    perRekeningAktif: '按活跃账户',
    belumAdaAkun: '暂无账户',
    hutangVsPiutang: '债务 vs 应收',
    perbandinganAktif: '当前比较',
    rekapSaldo: '账户余额汇总',
    saldoTerkini: '各账户最新余额',
    insightKeuangan: '财务洞察',
    analisisCerdas: '本月财务智能分析',
    skorKesehatan: '财务健康评分',
    top5Pengeluaran: '前5大支出',
    berdasarkanKategori: '按类别',
    rekapPeriode: '期间汇总',
    periode: '期间',
    kategoriFavorit: '收藏类别',
    totalAkun: '总账户数',
    totalTransaksi: '总交易数',
    semuaBulan: '全部月份',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('fincat_lang') || 'id');

  // Cycle through all languages
  const toggleLang = () => {
    const codes = LANGUAGES.map(l => l.code);
    const idx = codes.indexOf(lang);
    const next = codes[(idx + 1) % codes.length];
    setLang(next);
    localStorage.setItem('fincat_lang', next);
  };

  const setLangDirect = (code) => {
    setLang(code);
    localStorage.setItem('fincat_lang', code);
  };

  const t = (key) => {
    if (!key) return '';
    const val = translations[lang]?.[key] ?? translations['id']?.[key];
    if (!val) {
      if (import.meta.env.DEV) console.warn(`Missing translation: ${lang}.${key}`);
      return key;
    }
    return val;
  };

  const currentLang = LANGUAGES.find(l => l.code === lang) || LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, setLangDirect, t, currentLang, LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}