// Muted legacy utility palettes keep older screens aligned with the shared theme.
const enterprisePalette = (hue, saturation) => Object.fromEntries(
  [[50, 97], [100, 94], [200, 87], [300, 76], [400, 60], [500, 45], [600, 37], [700, 30], [800, 24], [900, 19], [950, 12]]
    .map(([shade, lightness]) => [shade, `hsl(${hue} ${saturation}% ${lightness}%)`])
);
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      borderRadius: {
        lg:  'var(--radius)',
        md:  'calc(var(--radius) - 2px)',
        sm:  'calc(var(--radius) - 4px)',
        '2xl': '0.75rem',
        '3xl': '0.875rem',
        '4xl': '1rem',
      },
      fontWeight: { light: '400', normal: '400', medium: '500', semibold: '600', bold: '600', extrabold: '600', black: '600' },
      colors: {
        'login-navy': 'rgb(var(--login-navy) / <alpha-value>)',
        'login-accent': 'rgb(var(--login-accent) / <alpha-value>)',
        'login-highlight': 'rgb(var(--login-highlight) / <alpha-value>)',
        'login-white': 'rgb(var(--login-white) / <alpha-value>)',
        blue: enterprisePalette(207, 52),
        sky: enterprisePalette(201, 52),
        cyan: enterprisePalette(193, 43),
        indigo: enterprisePalette(215, 34),
        purple: enterprisePalette(218, 30),
        violet: enterprisePalette(218, 30),
        emerald: enterprisePalette(158, 38),
        green: enterprisePalette(153, 35),
        teal: enterprisePalette(177, 33),
        red: enterprisePalette(0, 46),
        rose: enterprisePalette(355, 40),
        pink: enterprisePalette(343, 32),
        amber: enterprisePalette(35, 48),
        orange: enterprisePalette(28, 45),
        yellow: enterprisePalette(40, 46),
        success: 'hsl(var(--success) / <alpha-value>)',
        warning: 'hsl(var(--warning) / <alpha-value>)',
        info: 'hsl(var(--info) / <alpha-value>)',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card:        { DEFAULT: 'hsl(var(--card))',        foreground: 'hsl(var(--card-foreground))' },
        popover:     { DEFAULT: 'hsl(var(--popover))',     foreground: 'hsl(var(--popover-foreground))' },
        primary:     { DEFAULT: 'hsl(var(--primary))',     foreground: 'hsl(var(--primary-foreground))' },
        secondary:   { DEFAULT: 'hsl(var(--secondary))',   foreground: 'hsl(var(--secondary-foreground))' },
        muted:       { DEFAULT: 'hsl(var(--muted))',       foreground: 'hsl(var(--muted-foreground))' },
        accent:      { DEFAULT: 'hsl(var(--accent))',      foreground: 'hsl(var(--accent-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        border: 'hsl(var(--border))',
        input:  'hsl(var(--input))',
        ring:   'hsl(var(--ring))',
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
        sidebar: {
          DEFAULT:            'hsl(var(--sidebar-background))',
          foreground:         'hsl(var(--sidebar-foreground))',
          primary:            'hsl(var(--sidebar-primary))',
          'primary-foreground':'hsl(var(--sidebar-primary-foreground))',
          accent:             'hsl(var(--sidebar-accent))',
          'accent-foreground':'hsl(var(--sidebar-accent-foreground))',
          border:             'hsl(var(--sidebar-border))',
          ring:               'hsl(var(--sidebar-ring))',
        },
      },
      fontFamily: {
        heading: ['var(--font-heading)'],
        body:    ['var(--font-body)'],
        display: ['var(--font-display)'],
        mono:    ['var(--font-mono)'],
      },
      fontSize: {
        '2xs': ['0.625rem', { lineHeight: '1rem' }],
      },
      letterSpacing: {
        tighter: '-0.04em',
        tight:   '-0.02em',
        widest:  '0.12em',
      },
      boxShadow: {
        'xs':    'var(--shadow-xs)',
        'sm':    'var(--shadow-sm)',
        'DEFAULT':'var(--shadow-md)',
        'md':    'var(--shadow-md)',
        'lg':    'var(--shadow-lg)',
        'xl':    'var(--shadow-xl)',
        'premium': '0 20px 60px -12px rgba(14,165,233,0.15), 0 8px 25px -8px rgba(15,23,42,0.08)',
        'glow-sky':    '0 0 20px rgba(14,165,233,0.3)',
        'glow-green':  '0 0 20px rgba(16,185,129,0.3)',
        'glow-amber':  '0 0 20px rgba(245,158,11,0.3)',
        'inner-top':   'inset 0 1px 0 rgba(255,255,255,0.1)',
      },
      backgroundImage: {
        'gradient-premium': 'linear-gradient(135deg, #0F172A 0%, #1E293B 50%, #0F4C64 100%)',
        'gradient-sky':     'linear-gradient(135deg, #0EA5E9 0%, #0284C7 100%)',
        'gradient-success': 'linear-gradient(135deg, #10B981 0%, #059669 100%)',
        'gradient-danger':  'linear-gradient(135deg, #EF4444 0%, #DC2626 100%)',
        'gradient-amber':   'linear-gradient(135deg, #F59E0B 0%, #D97706 100%)',
        'gradient-indigo':  'linear-gradient(135deg, #6366F1 0%, #4F46E5 100%)',
        'gradient-mesh':    'radial-gradient(ellipse at 20% 50%, rgba(14,165,233,0.06) 0%, transparent 60%), radial-gradient(ellipse at 80% 20%, rgba(16,185,129,0.04) 0%, transparent 50%)',
      },
      keyframes: {
        'accordion-down': { from: { height: '0' },                               to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up':   { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        'fade-in-up':     { from: { opacity: '0', transform: 'translateY(12px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'fade-scale':     { from: { opacity: '0', transform: 'scale(0.96)' },     to: { opacity: '1', transform: 'scale(1)' } },
        'count-up':       { from: { opacity: '0', transform: 'translateY(6px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up':   'accordion-up 0.2s ease-out',
        'fade-in-up':     'fade-in-up 0.35s cubic-bezier(0.4,0,0.2,1) both',
        'fade-scale':     'fade-scale 0.3s ease-out both',
        'count-up':       'count-up 0.5s ease-out both',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
