export const guideHelp = {
  'dashboard-bulanan': { route: '/', module: 'Dashboard Bulanan', prepare: 'Catat transaksi, lalu samakan bulan, tahun, dan mata uang yang ingin dilihat.', example: 'Pendapatan Rp5 juta − pengeluaran Rp3 juta = cash flow Rp2 juta. Ini berbeda dari total saldo rekening.', issue: 'Angka terasa tidak cocok?', fix: 'Periksa periode, mata uang, dan jenis transaksi. Hutang baru dan transfer bukan pendapatan.' },
  'dashboard-tahunan': { route: '/tahunan', module: 'Dashboard Tahunan', prepare: 'Pastikan tanggal transaksi berada di tahun yang dipilih.', example: 'Bandingkan pengeluaran Januari dan Februari untuk menemukan bulan paling boros.', issue: 'Ada bulan kosong?', fix: 'Cek tanggal dan filter transaksi; bulan tanpa catatan belum tentu berarti tidak ada aktivitas.' },
  transaksi: { route: '/transaksi', module: 'Input Transaksi', prepare: 'Siapkan rekening, kategori yang sesuai, tanggal, dan nominal lebih dari nol.', example: 'Belanja Rp100.000 → Pengeluaran → pilih rekening dan kategori → simpan serta konfirmasi.', issue: 'Nominal atau data terkait ditolak?', fix: 'Pilih rekening, isi tanggal, dan pilih hutang/piutang/target yang sesuai. Pembayaran tidak boleh melebihi sisa kewajiban.' },
  hutang: { route: '/hutang', module: 'Hutang', prepare: 'Ketahui nama pemberi pinjaman, sisa kewajiban, dan jatuh tempo.', example: 'Hutang Rp2 juta dibayar Rp500.000 → sisa kewajiban Rp1,5 juta.', issue: 'Hutang masih aktif setelah dibayar?', fix: 'Cek apakah pembayaran dicatat sebagai Bayar Hutang dan terhubung ke hutang yang benar, bukan Pengeluaran biasa.' },
  piutang: { route: '/piutang', module: 'Piutang', prepare: 'Siapkan nama peminjam dan pilih piutang yang benar saat menerima pembayaran.', example: 'Piutang Rp1 juta diterima Rp250.000 → sisa tagihan Rp750.000.', issue: 'Sisa piutang tidak berkurang?', fix: 'Gunakan Terima Piutang pada Input Transaksi, bukan Pendapatan biasa; cek data piutang yang dipilih.' },
  tabungan: { route: '/tabungan', module: 'Tabungan', prepare: 'Tentukan nominal target, mata uang, tanggal mulai, dan tenggat yang realistis.', example: 'Target Rp12 juta, terkumpul Rp3 juta, sisa 9 bulan → kebutuhan rata-rata Rp1 juta per bulan.', issue: 'Setoran tidak masuk ke target?', fix: 'Pastikan transaksi berjenis Tabungan dan memilih target yang benar. Membuat target saja tidak mencatat setoran.' },
  budget: { route: '/budget', module: 'Budget', prepare: 'Pilih bulan dan tahun, kemudian isi anggaran tiap kategori dengan ikon pensil.', example: 'Anggaran makan Rp1 juta, realisasi Rp1,2 juta → kelebihan Rp200.000 (20%).', issue: 'Realisasi berbeda dari perkiraan?', fix: 'Samakan periode serta nama kategori dengan transaksi. Anggaran nol bukan bukti bahwa pengeluaran masih aman.' },
  saldo: { route: '/saldo', module: 'Saldo Rekening', prepare: 'Siapkan saldo awal dan mata uang setiap rekening; hindari menghitung transaksi lama dua kali.', example: 'Saldo awal Rp1 juta + pendapatan Rp500.000 − pengeluaran Rp200.000 = Rp1,3 juta.', issue: 'Saldo sistem berbeda dari bank?', fix: 'Buka Cross Check Saldo Bank, masukkan saldo aktual, lalu Cek Semua; telusuri transaksi hilang, ganda, atau salah rekening sebelum koreksi.' },
  transfer: { route: '/transfer', module: 'Transfer', prepare: 'Pilih dua rekening berbeda; perhatikan mata uang dan saldo yang tersedia.', example: 'Pindah Rp500.000 dari rekening A ke B bukan penghasilan baru.', issue: 'Pemasukan terlihat dobel?', fix: 'Jangan mencatat transfer internal sebagai Pendapatan. Periksa riwayat kedua rekening sebelum mencatat ulang.' },
  log: { route: '/log', module: 'Log Aktivitas', prepare: 'Ketahui waktu dan modul tempat perubahan dilakukan.', example: 'Filter aksi edit untuk menelusuri perubahan nominal transaksi.', issue: 'Tidak menemukan perubahan?', fix: 'Periksa filter waktu, aksi, dan modul; log hanya menjelaskan aktivitas yang tercatat.' },
  export: { route: '/riwayat', module: 'Riwayat Transaksi', prepare: 'Tentukan periode dan data yang akan diarsipkan; simpan file di lokasi aman.', example: 'Arsipkan laporan setiap akhir bulan sebelum melakukan perubahan besar.', issue: 'File terasa tidak lengkap?', fix: 'Cek filter periode serta modul yang dipilih, lalu buka file unduhan untuk memastikan isinya.' },
  pengaturan: { route: '/pengaturan', module: 'Pengaturan', prepare: 'Pastikan akun memiliki akses ke pengaturan yang dibutuhkan.', example: 'Tambahkan kategori Transportasi, lalu pilih kategori tersebut saat mencatat pengeluaran.', issue: 'Menu atau kategori tidak muncul?', fix: 'Cek jenis dan status kategori; sebagian menu dibatasi sesuai akses akun. Hubungi admin bila akses diperlukan.' }
};
export function openMoneyAssistant(question) { window.dispatchEvent(new CustomEvent('money-assistant-open', { detail: { question } })); }