// Sumber tunggal data paket & harga MONEY TRACKING.
export const WA_NUMBER = '6283812595110';

export const PRICING_TIERS = [
  {
    tier: 'NONE',
    label: 'Member Baru',
    isFree: true,
    price: 0,
    originalPrice: 0,
    period: 'gratis',
    accent: '#64748B',
    gradient: 'linear-gradient(135deg, #1E293B 0%, #475569 60%, #94A3B8 100%)',
    badge: 'Tanpa Role',
    discount: null,
    tagline: 'Lihat-lihat dulu, belum berpaket',
    waMsg: 'Halo Admin, saya member baru di MONEY TRACKING. Mohon dibantu pilih paket yang cocok 🙏',
    desc: 'Status awal setiap akun yang baru login dan belum memilih paket. Akses masih terbatas pada halaman informasi.',
    bestFor: 'Yang baru daftar dan ingin kenalan dulu dengan aplikasinya',
    outcome: 'Anda paham dulu fitur apa saja yang tersedia sebelum membayar — belum ada data keuangan yang bisa dicatat.',
    features: [
      { name: 'Panduan Fitur Lengkap', detail: 'Baca penjelasan tiap menu, cara pakai, tips, dan contoh kasus nyata.', included: true, highlight: true },
      { name: 'Halaman Paket & Harga', detail: 'Bandingkan isi paket dan lakukan pembayaran transfer kapan saja.', included: true, highlight: true },
      { name: 'Konsultasi & Bantuan Admin', detail: 'Tanya via WhatsApp untuk menentukan paket yang paling hemat untuk Anda.', included: true },
      { name: 'Dashboard Bulanan Real-time', detail: 'Melihat pemasukan, pengeluaran, dan sisa uang bulan berjalan.', included: false },
      { name: 'Input & Riwayat Transaksi', detail: 'Mencatat uang masuk/keluar beserta kategori dan rekeningnya.', included: false },
      { name: 'Saldo Rekening & Budget', detail: 'Memantau saldo tiap bank dan batas anggaran per kategori.', included: false },
      { name: 'Hutang, Piutang & Tabungan', detail: 'Kelola cicilan, tagihan orang lain, dan target menabung.', included: false },
      { name: 'Analitik Tahunan & Net Worth', detail: 'Tren tahunan, perbandingan antar tahun, dan kekayaan bersih.', included: false },
    ],
  },
  {
    tier: 'STAF',
    label: 'Paket Staf',
    price: 600000,
    originalPrice: 750000,
    period: 'selamanya',
    accent: '#059669',
    gradient: 'linear-gradient(135deg, #064E3B 0%, #059669 60%, #34D399 100%)',
    badge: 'Starter',
    discount: '20%',
    tagline: 'Mulai rapi mencatat',
    waMsg: 'Halo Admin, saya ingin membeli *Paket Staf* MONEY TRACKING. Mohon informasi lebih lanjut 🙏',
    desc: 'Cocok untuk pemula yang ingin mulai mencatat & memantau keuangan harian.',
    bestFor: 'Karyawan / pelajar bergaji tetap yang uangnya sering habis tanpa jejak',
    outcome: 'Anda tahu persis uang bulan ini masuk berapa, keluar ke pos apa, dan berapa sisa aman sampai gajian berikutnya.',
    features: [
      { name: 'Dashboard Bulanan Real-time', detail: 'Kartu ringkas pemasukan, pengeluaran, selisih, dan skor kesehatan keuangan bulan ini.', included: true, highlight: true },
      { name: 'Input Transaksi Pemasukan & Pengeluaran', detail: 'Catat nominal, tanggal, kategori, rekening, dan catatan — langsung memperbarui saldo.', included: true, highlight: true },
      { name: 'Riwayat & Laporan Transaksi', detail: 'Filter per bulan/kategori/rekening, lihat 5 pos pengeluaran terbesar Anda.', included: true },
      { name: 'Saldo Rekening Multi-Akun', detail: 'Pantau saldo tiap bank/e-wallet/tunai dalam satu layar, lengkap dengan logo bank.', included: true },
      { name: 'Budget Anggaran per Kategori', detail: 'Tetapkan plafon tiap pos; sistem mengingatkan saat pemakaian menyentuh 80%.', included: true },
      { name: 'Kelola Kategori Sendiri', detail: 'Buat kategori pemasukan/pengeluaran sesuai gaya hidup Anda.', included: true },
      { name: 'Kalender Keuangan', detail: 'Lihat transaksi harian dalam tampilan kalender agar pola boros terbaca.', included: true },
      { name: 'Panduan Fitur Lengkap', detail: 'Dokumentasi tiap fitur beserta tips penggunaan.', included: true },
      { name: 'Target Tabungan', detail: 'Simulasi menabung sampai target tercapai.', included: false },
      { name: 'Hutang & Piutang + Bunga', detail: 'Pencatatan cicilan, jatuh tempo, dan perhitungan bunga.', included: false },
      { name: 'Transfer Antar Rekening', detail: 'Pindah dana antar akun tanpa merusak laporan.', included: false },
      { name: 'Export Excel & Backup', detail: 'Unduh data ke Excel / Google Drive.', included: false },
      { name: 'Dashboard Tahunan, YoY & Net Worth', detail: 'Analitik jangka panjang dan kekayaan bersih.', included: false },
    ],
  },
  {
    tier: 'MASTER_2',
    label: 'Paket Master II',
    price: 1000000,
    originalPrice: 1300000,
    period: 'selamanya',
    accent: '#0891B2',
    gradient: 'linear-gradient(135deg, #164E63 0%, #0891B2 60%, #22D3EE 100%)',
    badge: 'Standar',
    discount: '23%',
    tagline: 'Kendali penuh arus kas',
    popular: false,
    waMsg: 'Halo Admin, saya ingin membeli *Paket Master II* MONEY TRACKING. Mohon informasi lebih lanjut 🙏',
    desc: 'Untuk yang serius kelola hutang, piutang, tabungan & butuh backup data.',
    bestFor: 'Pedagang, freelancer, atau siapa pun yang punya cicilan & sering meminjamkan uang',
    outcome: 'Anda tahu total hutang beserta bunganya, siapa yang belum bayar dan kapan jatuh tempo, serta berapa yang aman disisihkan untuk tabungan.',
    features: [
      { name: 'Semua fitur Paket Staf', detail: 'Dashboard bulanan, transaksi, saldo, budget, kalender, laporan.', included: true },
      { name: 'Manajemen Hutang + Bunga', detail: 'Catat pokok, bunga, tenor, dan cicilan; sisa hutang & tanggal jatuh tempo dihitung otomatis.', included: true, highlight: true },
      { name: 'Manajemen Piutang + Penagihan', detail: 'Pantau uang yang dipinjam orang, kirim rincian tagihan lewat WhatsApp/LINE/Instagram.', included: true, highlight: true },
      { name: 'Target Tabungan & Progress', detail: 'Tentukan nominal & tenggat; sistem menghitung setoran per bulan yang harus dipenuhi.', included: true, highlight: true },
      { name: 'Transfer Antar Rekening', detail: 'Pindah dana antar bank tanpa terhitung sebagai pemasukan/pengeluaran.', included: true, highlight: true },
      { name: 'Transaksi Rutin Otomatis', detail: 'Gaji, sewa, langganan tercatat sendiri setiap periode tanpa input manual.', included: true, highlight: true },
      { name: 'Cross-Check Saldo Bank', detail: 'Bandingkan saldo aplikasi vs mutasi bank untuk menemukan selisih pencatatan.', included: true, highlight: true },
      { name: 'Export Excel & Backup Drive', detail: 'Unduh seluruh data ke Excel atau simpan ke Google Drive untuk arsip.', included: true, highlight: true },
      { name: 'Laporan Keuangan Detail', detail: 'Laporan per kategori, budget, dan daftar jatuh tempo siap cetak/PDF.', included: true },
      { name: 'Pengaturan Lengkap', detail: 'Atur kategori, bunga default, tema, dan preferensi akun.', included: true },
      { name: 'Dashboard Tahunan & YoY', detail: 'Tren 12 bulan dan perbandingan antar tahun.', included: false },
      { name: 'Net Worth Tracker', detail: 'Aset dikurangi liabilitas beserta pergerakannya.', included: false },
      { name: 'Notifikasi Telegram Otomatis', detail: 'Ringkasan & peringatan langsung ke Telegram.', included: false },
    ],
  },
  {
    tier: 'MASTER_1',
    label: 'Paket Master I',
    price: 1300000,
    originalPrice: 1800000,
    period: 'selamanya',
    accent: '#6366F1',
    gradient: 'linear-gradient(135deg, #1E1B4B 0%, #4F46E5 60%, #818CF8 100%)',
    badge: 'Premium',
    discount: '28%',
    tagline: 'Akses penuh tanpa batas',
    popular: true,
    waMsg: 'Halo Admin, saya ingin membeli *Paket Master I* MONEY TRACKING. Mohon informasi lebih lanjut 🙏',
    desc: 'Akses PENUH tanpa batas — semua fitur premium + analitik tahunan mendalam.',
    bestFor: 'Pemilik usaha & keluarga dengan banyak rekening yang butuh gambaran kekayaan utuh',
    outcome: 'Anda melihat arah keuangan jangka panjang: kekayaan bersih naik atau turun, tahun ini lebih baik dari tahun lalu atau tidak, dan apa yang harus dibenahi.',
    features: [
      { name: 'Semua fitur Master II', detail: 'Termasuk hutang, piutang, tabungan, transfer, rutin, export.', included: true },
      { name: 'Dashboard Tahunan', detail: 'Grafik 12 bulan: arus kas, pos terbesar, bulan paling boros dan paling hemat.', included: true, highlight: true },
      { name: 'Year-over-Year Comparison', detail: 'Bandingkan tiap bulan dengan tahun sebelumnya untuk melihat kemajuan nyata.', included: true, highlight: true },
      { name: 'Net Worth Tracker', detail: 'Total aset (saldo + piutang + tabungan) dikurangi hutang, dipantau pergerakannya.', included: true, highlight: true },
      { name: 'Multi-Mata Uang & Kurs', detail: 'Catat dana valas dengan kurs yang Anda tentukan sendiri.', included: true, highlight: true },
      { name: 'Notifikasi Telegram Otomatis', detail: 'Ringkasan harian 07.00 WIB, peringatan jatuh tempo, dan tiap transaksi baru.', included: true, highlight: true },
      { name: 'Ringkasan Email Bulanan', detail: 'Laporan bulanan dikirim otomatis ke email Anda setiap awal bulan.', included: true, highlight: true },
      { name: 'Asisten AI Keuangan Mendalam', detail: 'Analisis kondisi keuangan Anda dan saran perbaikan berbasis data sendiri.', included: true, highlight: true },
      { name: 'Log Aktivitas & Audit', detail: 'Jejak setiap perubahan data untuk keamanan dan penelusuran.', included: true },
      { name: 'Prioritas Dukungan Admin', detail: 'Pertanyaan Anda ditangani lebih dulu lewat konsultasi in-app & WhatsApp.', included: true },
    ],
  },
];

export const TIER_MAP = { NONE: 'none', STAF: 'staf', MASTER_2: 'master_2', MASTER_1: 'master_1' };
export const TIER_LEVEL = { none: 0, staf: 1, master_2: 2, master_1: 3, super_master: 4 };
export const formatRp = (n) => 'Rp ' + Number(n || 0).toLocaleString('id-ID');